name: Publicar no PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # 🔥 ISSO ATIVA O OIDC

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar build
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build do pacote
        run: python -m build

      - name: Publicar no PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
